name = "Tokyo Night"
version = "0.1.0"

authors = [
    "Ahum Maitra (@TheAhumMaitra) theahummaitra@gmail.com",
]

wallpapers_source = ["https://github.com/tokyo-night/wallpapers","https://github.com/atraxsrc/tokyonight-wallpapers", ""]

[gtk]
theme_name = "Yaru-blue-dark"
icon_theme = "Yaru-blue"