-- DO NOT EDIT THIS FILE
return {
  {
    "rose-pine/neovim",
    name = "rose-pine",
    priority = 1000, -- make sure it loads first
    config = function()
      vim.cmd.colorscheme("rose-pine")
    end,
  },
}
