name = "Dracula"
version = "0.1.0"

authors = [
    "Ahum Maitra (@TheAhumMaitra) theahummaitra@gmail.com",
]

license = "GPL-3.0-or-later"
wallpapers_sources = ["https://github.com/dracula/wallpaper"]

[settings]
script = "activate.sh"
interpreter = "bash"

[gtk]
theme_name = "Yaru-purple-dark"
icon_theme = "Yaru-purple"