-- DO NOT EDIT THIS FILE
return {
  {
    "aliqyan-21/darkvoid.nvim",
    name = "darkvoid",
    priority = 1000, -- make sure it loads first
    config = function()
      vim.cmd.colorscheme("darkvoid")
    end,
  },
}

