layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
layerrule = blur on, match:namespace com.aurora.keybinds_help
layerrule = ignore_alpha 0, match:namespace com.aurora.keybinds_help
layerrule = blur on, match:namespace wlogout
layerrule = ignore_alpha 0, match:namespace wlogout
layerrule = blur on, match:namespace com.aurora.search
layerrule = ignore_alpha 0, match:namespace com.aurora.search