$configs = $HOME/.config/hypr/configs

# load default keybinds
source = $configs/keybinds.conf

# load all default plugin configuration
source = $configs/plugins.conf

# load default monitor configuration (you can use nwg-look)
source = $HOME/.config/hypr/monitor.conf

# load autostart programs config
source = $configs/autostart.conf

# load all environment all variables
source = $configs/env_vars.conf

# load default decorations
source = $configs/look_and_feel.conf

# load layouts configurations
source = $configs/layout_configs.conf

# load input configuration 
source = $configs/input.conf

# load default window rules
source = $configs/window_rules.conf

# load default animations 
source = $configs/animation.conf
