name = "Rose Pine"
version = "0.1.0"

authors = [
    "Ahum Maitra (@TheAhumMaitra) theahummaitra@gmail.com",
]

license = "GPL-3.0-or-later"

wallpapers_sources = ["https://github.com/rose-pine/wallpapers"]

[gtk]
theme_name = "Yaru-blue-dark"
icon_theme = "Yaru-blue-dark"

[vscode]
publisher = "mvllow"
extension_name = "rose-pine"
theme_name = "Rosé Pine"
