-- DO NOT EDIT THIS FILE
return {
  {
    "Mofiqul/dracula.nvim",
    name = "dracula",
    priority = 1000, -- make sure it loads first
    config = function()
      vim.cmd.colorscheme("dracula")
    end,
  },
}
