-- DO NOT EDIT THIS FILE
return {
  {
    "folke/tokyonight.nvim",
    name = "tokyonight",
    priority = 1000, -- make sure it loads first
    config = function()
      vim.cmd.colorscheme("tokyonight-night")
    end,
  },
}
