name = "Catppuccin Mocha"
version = "0.1.0"

authors = [
    "Ahum Maitra (@TheAhumMaitra) theahummaitra@gmail.com",
]

license = "GPL-3.0-or-later"

wallpapers_sources = ["https://github.com/VipinVIP/wallpapers", "https://github.com/orangci/walls-catppuccin-mocha"]

[gtk]
theme_name = "Yaru-purple-dark"
icon_theme = "Yaru-purple"