name = "Nord"
version = "0.1.0"

authors = [
    "Ahum Maitra (@TheAhumMaitra) theahummaitra@gmail.com",
]

license = "GPL-3.0-or-later"
wallpapers_sources = ["https://github.com/linuxdotexe/nordic-wallpapers"]

[gtk]
theme_name = "Yaru-blue-dark"
icon_theme = "Yaru-blue-dark"

[vscode]
publisher = "arcticicestudio"
extension_name = "nord-visual-studio-code"
theme_name = "Nord"
