-- DO NOT EDIT THIS FILE
return {
  {
    "neanias/everforest-nvim",
    name = "everforest",
    priority = 1000, -- make sure it loads first
    config = function()
      vim.cmd.colorscheme("everforest")
    end,
  },
}
