-- DO NOT EDIT THIS FILE
return {
  {
    "shaunsingh/nord.nvim",
    name = "nord",
    priority = 1000, -- make sure it loads first
    config = function()
      vim.cmd.colorscheme("nord")
    end,
  },
}
