-- DO NOT EDIT THIS FILE
return {
  {
    "ellisonleao/gruvbox.nvim",
    name = "gruvbox",
    priority = 1000, -- make sure it loads first
    config = function()
      vim.cmd.colorscheme("gruvbox")
    end,
  },
}
